name: Run tests and upload coverage

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
      
      - name: npm install, build and test
        run: |
            npm install
            npm run build --if-present
            npm test -- --coverage
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      
        

        
  
  






